name: CannonRTP
version: ${project.version}
author: MagmaGuy
main: com.magmaguy.cannonrtp.CannonRTP
api-version: '1.21'
softdepend: [WorldGuard, Towny, Lands, GriefPrevention, HuskTowns, HuskClaims, FreeMinecraftModels]

commands:
  cannonrtp:
    description: Manages CannonRTP cannons and debugging.
    usage: /cannonrtp
    aliases: [crtp, wc]

permissions:
  cannonrtp.admin:
    description: Allows admins to manage CannonRTP.
    default: op
  cannonrtp.use:
    description: Allows players to use CannonRTPs.
    default: true
